export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    ME: "/auth/me",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_VERIFICATION: "/auth/resend-verification",
  },
  TOURS: {
    LIST: "/tours",
    FEATURED: "/tours/featured",
    HOT: "/tours/hot",
    DETAIL: (id: string) => `/tours/${id}`,
    CATEGORIES: "/tour-categories",
    BY_CATEGORY_SLUG: (slug: string) => `/tour-categories/${slug}/tours`,
    SCHEDULES: (id: number | string) => `/tours/${id}/schedules`,
    CHECK_AVAILABILITY: (id: number | string) => `/tours/${id}/check-availability`,
    RATINGS: (id: number | string) => `/tours/${id}/ratings`,
    RATING_STATS: (id: number | string) => `/tours/${id}/rating-stats`,
  },
  USER: {
    PROFILE: "/user/profile",
    UPDATE_PROFILE: "/user/profile",
    AVATAR: "/user/profile/avatar",
    CHANGE_PASSWORD: "/user/password",
    RATINGS: "/user/ratings",
    FAVORITES: "/user/favorites",
    FAVORITES_CHECK: "/user/favorites/check", // Use query params ?location_id= or ?tour_id=
  },
  BOOKINGS: {
    CALCULATE: "/bookings/calculate",
    STORE: "/bookings",
    USER_LIST: "/user/bookings",
    DETAIL: (id: number | string) => `/user/bookings/${id}`,
    DETAIL_BY_CODE: (bookingCode: string) => `/user/bookings/code/${bookingCode}`,
    INVOICE: (id: number | string) => `/user/bookings/${id}/invoice`,
    CANCEL: (id: number | string) => `/user/bookings/${id}/cancel`,
  },
  PAYMENTS: {
    CREATE: "/payments/create",
    STATUS: (transactionCode: string) => `/payments/status/${transactionCode}`,
    RETRY: (bookingCode: string) => `/payments/retry/${bookingCode}`,
  },
  NOTIFICATIONS: {
    LIST: "/user/notifications",
    UNREAD_COUNT: "/user/notifications/unread-count",
    MARK_READ: (id: number | string) => `/user/notifications/${id}/read`,
    MARK_ALL_READ: "/user/notifications/read-all",
    DELETE: (id: number | string) => `/user/notifications/${id}`,
  },
  LOCATIONS: {
    LIST: "/locations",
    FEATURED: "/locations/featured",
    DETAIL: (slug: string) => `/locations/${slug}`,
    CATEGORIES: "/categories",
    IMAGES: (id: number) => `/locations/${id}/images`,
    RATINGS: (id: number) => `/locations/${id}/ratings`,
    RATING_STATS: (id: number) => `/locations/${id}/rating-stats`,
    NEARBY_BY_ID: (id: number) => `/locations/${id}/nearby`,
    NEARBY: "/locations/nearby",
    RECORD_VIEW: (id: number) => `/locations/${id}/view`,
  },
  RATINGS: {
    CHECK: "/ratings/check",
    STORE: "/ratings",
    UPDATE: (id: number | string) => `/ratings/${id}`,
    DELETE: (id: number | string) => `/ratings/${id}`,
    HELPFUL: (id: number) => `/ratings/${id}/helpful`,
  },
  UPLOAD: {
    IMAGES: "/upload/images",
  },
  STATISTICS: "/statistics",
  BLOG: {
    LIST: "/blog",
    CATEGORIES: "/blog/categories",
    DETAIL: (slug: string) => `/blog/${slug}`,
  },
  SEARCH: {
    LIST: "/search",
    SUGGESTIONS: "/search/suggestions",
    POPULAR: "/search/popular",
    TRENDING: "/search/trending",
  },
  CONTACTS: "/contacts",
  LANDING_PAGES: {
    DETAIL: (slug: string) => `/landing-pages/${slug}`,
  },
  RECOMMENDATIONS: "/recommendations",
};
